import { useEffect, useMemo, useState, type CSSProperties } from 'react';
import { ArrowLeft, ArrowRight, BrainCircuit, Check, Code2, FileCode2, Gauge, MessageSquareText, RotateCcw, Sparkles, Target, Trophy, UsersRound, Wrench } from 'lucide-react';
import type { Difficulty, PlacementAnalysis, QuestionType, TrainingEvaluation, TrainingQuestion } from '../types/placement';
import { evaluateTrainingAnswer, generateTrainingQuestion } from '../services/api';
import { saveTrainingAttempt } from '../services/storage';
import type { PageKey } from '../components/Sidebar';

const TYPES: Array<{type:QuestionType; label:string; desc:string; icon:typeof BrainCircuit}> = [
  {type:'mcq',label:'MCQ',desc:'Fast screening',icon:Gauge}, {type:'coding',label:'Coding',desc:'Timed problem',icon:Code2}, {type:'technical',label:'Technical',desc:'Concept depth',icon:Wrench}, {type:'behavioral',label:'Behavioral',desc:'Communication',icon:UsersRound}, {type:'project',label:'Project',desc:'Experience deep dive',icon:FileCode2}, {type:'system-design',label:'System Design',desc:'Architecture thinking',icon:BrainCircuit}, {type:'case',label:'Case / Debug',desc:'Reasoning under pressure',icon:MessageSquareText},
];

export function Training({ analysis, onNavigate }: { analysis?: PlacementAnalysis; onNavigate:(page:PageKey)=>void }) {
  const [type,setType]=useState<QuestionType>('mcq'); const [difficulty,setDifficulty]=useState<Difficulty>('medium'); const [question,setQuestion]=useState<TrainingQuestion>(); const [answer,setAnswer]=useState(''); const [selectedOption,setSelectedOption]=useState<number>(); const [evaluation,setEvaluation]=useState<TrainingEvaluation>(); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [questionCount,setQuestionCount]=useState(0); const [streak,setStreak]=useState(0); const [recentIds,setRecentIds]=useState<string[]>([]);
  useEffect(()=>{ if(analysis) setQuestion(undefined); },[analysis]);
  const selectedMeta=useMemo(()=>TYPES.find(x=>x.type===type),[type]);
  if(!analysis) return <section className="panel empty-state large"><Target size={33}/><strong>Analyse a job before entering the trainer</strong><span>The trainer uses the role analysis and your skill gaps to generate targeted questions.</span><button className="primary-btn" onClick={()=>onNavigate('analyze')}>Analyse a role <ArrowRight size={15}/></button></section>;
  const generate=async()=>{setError('');setEvaluation(undefined);setAnswer('');setSelectedOption(undefined);setLoading(true);try{const q=await generateTrainingQuestion({type,difficulty,job:analysis.job,skillGap:analysis.skillGap,resume:analysis.resume,recentQuestionIds:recentIds});setQuestion(q);setRecentIds(prev=>[...prev,q.id].slice(-8));setQuestionCount(n=>n+1);}catch(e){setError(e instanceof Error?e.message:'Could not generate a question.')}finally{setLoading(false);}};
  const submit=async()=>{if(!question)return;setError('');setLoading(true);try{const result=await evaluateTrainingAnswer({type,difficulty,job:analysis.job,skillGap:analysis.skillGap,resume:analysis.resume,question,answer,selectedOption});setEvaluation(result);setStreak(result.score>=70?streak+1:0);saveTrainingAttempt({id:`ATT-${Date.now()}`,createdAt:new Date().toISOString(),score:result.score,type,role:analysis.job.role,verdict:result.verdict});}catch(e){setError(e instanceof Error?e.message:'Could not evaluate this answer.')}finally{setLoading(false);}};
  const reset=()=>{setQuestion(undefined);setEvaluation(undefined);setAnswer('');setSelectedOption(undefined);setError('');};
  return <div className="page-stack training-page">
    <section className="trainer-hero"><div><div className="kicker"><Sparkles size={14}/> ROLE-SPECIFIC TRAINING</div><div className="trainer-title-row"><div><h2>{analysis.job.role}</h2><p>{analysis.job.company||'Target opportunity'} · question difficulty calibrated to your current gaps</p></div><div className="trainer-stats"><div><b>{questionCount}</b><span>questions</span></div><div><b>{streak}</b><span>current streak</span></div></div></div></div><button className="ghost-btn" onClick={()=>onNavigate('role')}><ArrowLeft size={15}/> Back to role intelligence</button></section>
    <div className="training-layout">
      <aside className="panel trainer-controls"><div className="panel-heading"><div><div className="section-label">Training control</div><h3>Choose the drill</h3></div><Target size={18}/></div><div className="control-group"><label className="field-label">Question type</label><div className="type-grid">{TYPES.map(item=>{const Icon=item.icon;return <button key={item.type} className={`type-card ${type===item.type?'selected':''}`} onClick={()=>{setType(item.type);setQuestion(undefined);setEvaluation(undefined);setAnswer('');setSelectedOption(undefined);}}><span className="type-icon"><Icon size={16}/></span><span><b>{item.label}</b><small>{item.desc}</small></span></button>})}</div></div><div className="control-group"><label className="field-label">Difficulty</label><div className="difficulty-row">{(['easy','medium','hard'] as Difficulty[]).map(d=><button key={d} className={`difficulty ${difficulty===d?'active':''}`} onClick={()=>setDifficulty(d)}>{d}</button>)}</div></div><div className="trainer-context"><span className="status-dot"/><div><b>Grounded to {analysis.job.role}</b><span>Focus: {(analysis.job.focusAreas[0]?.area || analysis.skillGap.priorityGaps[0]?.skill || 'role fundamentals')}</span></div></div><button className="primary-btn wide" disabled={loading} onClick={generate}>{loading&&!question?<><Sparkles className="spin" size={15}/> Building question...</>:<><Sparkles size={15}/> Generate next question</>}</button></aside>

      <main className="trainer-main">
        {!question ? <section className="panel question-empty"><div className="question-empty-orb"><div className="orb-ring r1"/><div className="orb-ring r2"/><div className="orb-ring r3"/><Sparkles size={26}/></div><div className="section-label">TRAINING ENGINE ARMED</div><h3>Generate a {selectedMeta?.label.toLowerCase()} question for this role.</h3><p>{selectedMeta?.desc}. The prompt is generated from the target role, extracted requirements and your current skill gaps.</p><button className="primary-btn" onClick={generate}>Generate question <ArrowRight size={15}/></button></section> : <>
          <section className="panel question-panel"><div className="question-meta"><div><span className={`question-type ${question.type}`}>{question.type.replace('-', ' ')}</span><span className="question-difficulty">{question.difficulty}</span></div><span className="question-time"><Gauge size={14}/> {question.timeLimitMinutes} min</span></div><div className="question-title"><span>Challenge {String(questionCount).padStart(2,'0')}</span><h3>{question.title}</h3></div><p className="question-prompt">{question.prompt}</p>{question.examples?.length ? <div className="examples"><div className="section-label">Examples</div>{question.examples.map((ex,i)=><div className="example-box" key={i}><span>Input</span><code>{ex.input}</code><span>Output</span><code>{ex.output}</code></div>)}</div>:null}{question.starterCode&&<div className="code-editor"><div className="code-head"><span>starter.ts</span><span>candidate workspace</span></div><textarea value={answer||question.starterCode} onChange={e=>setAnswer(e.target.value)} spellCheck={false}/></div>}{question.type==='mcq'&&question.options?.length ? <div className="options-list">{question.options.map((option,i)=><button key={option} className={`option-row ${selectedOption===i?'selected':''}`} onClick={()=>setSelectedOption(i)}><span>{String.fromCharCode(65+i)}</span><strong>{option}</strong>{selectedOption===i&&<Check size={16}/>}</button>)}</div>:question.type!=='coding'&&<div className="answer-box"><div className="answer-box-head"><span>Your response</span><span>{answer.length.toLocaleString()} chars</span></div><textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Structure your answer with reasoning, evidence, trade-offs and the result..." rows={8}/></div>}<div className="question-actions"><button className="secondary-btn" onClick={reset}><RotateCcw size={14}/> Reset</button><button className="primary-btn" disabled={loading || (question.type==='mcq'?selectedOption==null:!answer.trim())} onClick={submit}>{loading?<><Sparkles className="spin" size={14}/> Evaluating...</>:<><Trophy size={14}/> Evaluate answer <ArrowRight size={15}/></>}</button></div></section>
          {evaluation&&<section className="panel evaluation-panel"><div className="evaluation-score"><div className="score-ring" style={{'--score':`${evaluation.score}%`} as CSSProperties}><div><b>{evaluation.score}</b><span>/100</span></div></div><div><div className="kicker"><Check size={13}/> EVALUATED</div><h3>{evaluation.verdict.replace('-', ' ')}</h3><p>{evaluation.feedback}</p></div></div><div className="evaluation-grid"><div><div className="section-label">What worked</div>{evaluation.strengths.map(x=><div className="eval-row" key={x}><Check size={13}/>{x}</div>)}</div><div><div className="section-label">What to improve</div>{evaluation.improvements.map(x=><div className="eval-row warning" key={x}><ArrowRight size={13}/>{x}</div>)}</div></div><div className="ideal-answer"><div className="section-label">Model answer shape</div><p>{evaluation.idealAnswer}</p></div><button className="primary-btn" onClick={generate}>Next question <ArrowRight size={15}/></button></section>}
        </>}
        {error&&<div className="inline-error">{error}</div>}
      </main>
    </div>
  </div>;
}
